CREATE TABLE IF NOT EXISTS Brands (
    BRAND_ID int(11) NOT NULL AUTO_INCREMENT,
    Name NVARCHAR(256) NOT NULL,
    PRIMARY KEY (BRAND_ID)
);

CREATE TABLE IF NOT EXISTS Brand_Quantity_Time_Received (
    BRAND_ID int(11) NOT NULL,
    QUANTITY int(11) NOT NULL,
    TIME_RECEIVED DATETIME NOT NULL,
    PRIMARY KEY (BRAND_ID, QUANTITY, TIME_RECEIVED),
    FOREIGN KEY (BRAND_ID)
        REFERENCES Brands(BRAND_ID)
        ON DELETE CASCADE
);